export function getData() {
  const rowData = [
    {
        "RONumber": "6478190",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Kiaan French",
        "Advisor": "Eric Sanders",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "3:15",
        "HangTag": "320",
        "ShortVIN": "...X0W1RW",
        "VIN": "2G1LKAZS78CX0W1RW",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569192",
        "AppointmentTime": "4:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Pending",
        "WarrantyStatusDealer": "Submited to OEM",
        "PayType": "C/W",
        "Warranty": "$683.27 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$489.98 "
    },
    {
        "RONumber": "6478191",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Gus Charlton",
        "Advisor": "Susan Barber",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "321",
        "ShortVIN": "...WTDXGR",
        "VIN": "2C3B94MJPG4WTDXGR",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569193",
        "AppointmentTime": "11:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$51.88 "
    },
    {
        "RONumber": "6478192",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Yosef Henderson",
        "Advisor": "King Villanueva",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "322",
        "ShortVIN": "...SWLNT7",
        "VIN": "7SAHUKME2C2SWLNT7",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569194",
        "AppointmentTime": "3:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Rental",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$384.32 "
    },
    {
        "RONumber": "6478193",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Aarron Bannister",
        "Advisor": "Susan Barber",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "323",
        "ShortVIN": "...XYR8FK",
        "VIN": "1FA9H1NB4RMXYR8FK",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569194",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "4-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Pending",
        "WarrantyStatusDealer": "Submited to OEM",
        "PayType": "W",
        "Warranty": "$359.42 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478193",
        "Line Number": "2",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Aarron Bannister",
        "Advisor": "Susan Barber",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "323",
        "ShortVIN": "...XYR8FK",
        "VIN": "1FA9H1NB4RMXYR8FK",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569195",
        "AppointmentTime": "1:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Pending",
        "WarrantyStatusDealer": "Submited to OEM",
        "PayType": "W",
        "Warranty": "$721.99 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478194",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Janelle Kirkpatrick",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "324",
        "ShortVIN": "...4G65Y0",
        "VIN": "2FCNWR5NXNG4G65Y0",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569196",
        "AppointmentTime": "5:10 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$190.52 "
    },
    {
        "RONumber": "6478195",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Nelson Weber",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "325",
        "ShortVIN": "...Z0L7C3",
        "VIN": "1M339JACPDBZ0L7C3",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569197",
        "AppointmentTime": "5:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Returned",
        "PayType": "W",
        "Warranty": "$837.92 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478196",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Shah Strickland",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "326",
        "ShortVIN": "...6K3H8H",
        "VIN": "3MZ4VN5U7S86K3H8H",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569198",
        "AppointmentTime": "12:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$538.62 "
    },
    {
        "RONumber": "6478197",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Ikra Rich",
        "Advisor": "Eliza George",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "327",
        "ShortVIN": "...VBKU7P",
        "VIN": "94DAGC4XK70VBKU7P",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569199",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Rental",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$59.89 "
    },
    {
        "RONumber": "6478198",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Dealer Vehicle",
        "Advisor": "Eliza George",
        "Service Type": "BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "328",
        "ShortVIN": "...SVLK5W",
        "VIN": "ZCGG4807Z88SVLK5W",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569200",
        "AppointmentTime": "8:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Submited",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Defaut",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "I",
        "Warranty": "",
        "Internal": "$71.51 ",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478199",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Jardel Wiley",
        "Advisor": "King Villanueva",
        "Service Type": "MR/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "329",
        "ShortVIN": "...KC0X5E",
        "VIN": "JHFPHPE0362KC0X5E",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569201",
        "AppointmentTime": "10:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$78.80 "
    },
    {
        "RONumber": "6478200",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Suzanna Norris",
        "Advisor": "Eric Sanders",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "330",
        "ShortVIN": "...TJH78T",
        "VIN": "2G2APETCVKMTJH78T",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569202",
        "AppointmentTime": "10:00 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Pending",
        "PayType": "C/W",
        "Warranty": "$58.69 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$48.97 "
    },
    {
        "RONumber": "6478201",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Arooj Case",
        "Advisor": "Latisha Wyatt",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "331",
        "ShortVIN": "...2YAHHU",
        "VIN": "1VWVL6V2D8H2YAHHU",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Blazer",
        "AppointmentID": "9187569203",
        "AppointmentTime": "2:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Pending",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Pending",
        "PayType": "C/W",
        "Warranty": "$144.26 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$51.88 "
    },
    {
        "RONumber": "6478202",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Ruth Eaton",
        "Advisor": "Eric Sanders",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "332",
        "ShortVIN": "...BZL0LZ",
        "VIN": "JHC2X4D8G7FBZL0LZ",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569204",
        "AppointmentTime": "12:00 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Submited",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "S",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "$709.39 ",
        "Customer Pay": "$34.15 "
    },
    {
        "RONumber": "6478203",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Kara Gould",
        "Advisor": "Eric Sanders",
        "Service Type": "MR/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "333",
        "ShortVIN": "...LW1DYS",
        "VIN": "ZJM69LCW41PLW1DYS",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569205",
        "AppointmentTime": "11:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$79.94 "
    },
    {
        "RONumber": "6478204",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Bethanie Richardson",
        "Advisor": "Susan Barber",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "334",
        "ShortVIN": "...VCX8ZP",
        "VIN": "1J4BU81BB4WVCX8ZP",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569206",
        "AppointmentTime": "8:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Rental",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Pending",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "S",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "$811.42 ",
        "Customer Pay": "$56.07 "
    },
    {
        "RONumber": "6478205",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Milena Findlay",
        "Advisor": "Eliza George",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "335",
        "ShortVIN": "...VYD6HR",
        "VIN": "JHMBFWA6AWKVYD6HR",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569207",
        "AppointmentTime": "1:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Shuttle",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$49.09 "
    },
    {
        "RONumber": "6478206",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Ashleigh Harding",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "336",
        "ShortVIN": "...AV9Z18",
        "VIN": "3P34EHCZC46AV9Z18",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569208",
        "AppointmentTime": "12:00 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Submited",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "S",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "$220.98 ",
        "Customer Pay": "$83.96 "
    },
    {
        "RONumber": "6478207",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Leigha Plant",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "337",
        "ShortVIN": "...GD0HNB",
        "VIN": "5NPGEAWE362GD0HNB",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569209",
        "AppointmentTime": "5:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Corrected",
        "PayType": "C/W",
        "Warranty": "$95.75 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$96.28 "
    },
    {
        "RONumber": "6478208",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Livia Munro",
        "Advisor": "King Villanueva",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "338",
        "ShortVIN": "...PK62DY",
        "VIN": "4UZTJF7BH9FPK62DY",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569210",
        "AppointmentTime": "8:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$87.28 "
    },
    {
        "RONumber": "6478209",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Bobbie Hewitt",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "339",
        "ShortVIN": "...E9LWUP",
        "VIN": "2CNEW4B7X8UE9LWUP",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569211",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$36.73 "
    },
    {
        "RONumber": "6478210",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Rhona Bray",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "340",
        "ShortVIN": "...K1WGW4",
        "VIN": "795JTHVMGDPK1WGW4",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569212",
        "AppointmentTime": "4:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$69.32 "
    },
    {
        "RONumber": "6478211",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Varun Gordon",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "341",
        "ShortVIN": "...5KYMTF",
        "VIN": "93H85TV1MDA5KYMTF",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569213",
        "AppointmentTime": "4:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Completed",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$55.38 "
    },
    {
        "RONumber": "6478212",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Kathleen Jacobson",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "342",
        "ShortVIN": "...MAEWE4",
        "VIN": "1GTK6C290PKMAEWE4",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569214",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Rejected",
        "WarrantyStatusDealer": "Submited to OEM",
        "PayType": "C/W",
        "Warranty": "$246.57 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$98.56 "
    },
    {
        "RONumber": "6478213",
        "Line Number": "1",
        "ROStatus": "Pre Invoice",
        "CustomerName": "Lisa-Marie Burgess",
        "Advisor": "Susan Barber",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "343",
        "ShortVIN": "...6ZTHTA",
        "VIN": "2FTBYFZ1F1A6ZTHTA",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Blazer",
        "AppointmentID": "9187569215",
        "AppointmentTime": "5:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Completed",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$71.89 "
    },
    {
        "RONumber": "6478214",
        "Line Number": "1",
        "ROStatus": "With Advisor",
        "CustomerName": "Dealer Vehicle",
        "Advisor": "Eric Sanders",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "344",
        "ShortVIN": "...PVLCU6",
        "VIN": "WBAL8PYD28KPVLCU6",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569216",
        "AppointmentTime": "8:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Joe Smith",
        "TechStatus": "Assigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "I",
        "Warranty": "",
        "Internal": "$480.11 ",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478215",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Vivek Martin",
        "Advisor": "Eliza George",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "345",
        "ShortVIN": "...DYLZAZ",
        "VIN": "6U9CTYEKMVSDYLZAZ",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569217",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Martin Hernandez",
        "TechStatus": "Assigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$67.81 "
    },
    {
        "RONumber": "6478216",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Nahla Wilks",
        "Advisor": "Eric Sanders",
        "Service Type": "MR/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:15",
        "HangTag": "346",
        "ShortVIN": "...77ASEV",
        "VIN": "ZD4HSTKAG6R77ASEV",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569218",
        "AppointmentTime": "1:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Maria Sanchez",
        "TechStatus": "Assigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Pending",
        "PayType": "W",
        "Warranty": "$287.56 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478217",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Luella Goodman",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "347",
        "ShortVIN": "...XNGY49",
        "VIN": "1XKWY8GWCGGXNGY49",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569219",
        "AppointmentTime": "10:00 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Jeff Booker",
        "TechStatus": "Assigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Requested",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$301.21 "
    },
    {
        "RONumber": "6478218",
        "Line Number": "1",
        "ROStatus": "With Advisor",
        "CustomerName": "Prince Beltran",
        "Advisor": "Eliza George",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "348",
        "ShortVIN": "...RGB40D",
        "VIN": "ZLA6H1BL33XRGB40D",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569220",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Joe Smith",
        "TechStatus": "Assigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Requested",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$577.93 "
    },
    {
        "RONumber": "6478219",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Maison Driscoll",
        "Advisor": "King Villanueva",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "349",
        "ShortVIN": "...FFKUKL",
        "VIN": "JF6GCNXW6L1FFKUKL",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569221",
        "AppointmentTime": "3:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Joe Smith",
        "TechStatus": "Assigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$246.57 "
    },
    {
        "RONumber": "6478220",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Subhan Golden",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "350",
        "ShortVIN": "...3RSKT9",
        "VIN": "1M2R5LNT76U3RSKT9",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569222",
        "AppointmentTime": "10:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Maria Sanchez",
        "TechStatus": "Assigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$258.05 "
    },
    {
        "RONumber": "6478221",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Marcus North",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "351",
        "ShortVIN": "...97R3BK",
        "VIN": "YV1RW40CE6797R3BK",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569223",
        "AppointmentTime": "1:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Jeff Booker",
        "TechStatus": "Assigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$36.73 "
    },
    {
        "RONumber": "6478222",
        "Line Number": "1",
        "ROStatus": "With Advisor",
        "CustomerName": "Lewis Dillon",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "352",
        "ShortVIN": "...T5VCJ9",
        "VIN": "8AG2FTNV7DXT5VCJ9",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569224",
        "AppointmentTime": "3:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Joe Smith",
        "TechStatus": "Assigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$78.73 "
    },
    {
        "RONumber": "6478223",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Dealer Vehicle",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "353",
        "ShortVIN": "...DYNZ11",
        "VIN": "1G4S537NVS6DYNZ11",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569225",
        "AppointmentTime": "12:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Martin Hernandez",
        "TechStatus": "Assigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Requested",
        "TransportationType": "Loaner",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "I",
        "Warranty": "",
        "Internal": "$69.59 ",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478224",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Mehdi Cox",
        "Advisor": "Eric Sanders",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "354",
        "ShortVIN": "...27R5KD",
        "VIN": "4V21MZ3G1GS27R5KD",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569226",
        "AppointmentTime": "1:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Maria Sanchez",
        "TechStatus": "Assigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Requested",
        "TransportationType": "Loaner",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$70.64 "
    },
    {
        "RONumber": "6478225",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Casper Mcfarlane",
        "Advisor": "Eliza George",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "355",
        "ShortVIN": "...ZZKSUY",
        "VIN": "2WK9GRMRBNFZZKSUY",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Blazer",
        "AppointmentID": "9187569227",
        "AppointmentTime": "2:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "In Progress",
        "Tech": "Jeff Booker",
        "TechStatus": "Assigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Loaner",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$70.02 "
    },
    {
        "RONumber": "6478226",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Camron Bryant",
        "Advisor": "King Villanueva",
        "Service Type": "MR/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "356",
        "ShortVIN": "...VH8K9J",
        "VIN": "KN3NB0C8L4KVH8K9J",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569228",
        "AppointmentTime": "9:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Loaner",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Pending",
        "PayType": "W",
        "Warranty": "$388.92 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478227",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Yousef Romero",
        "Advisor": "Latisha Wyatt",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "357",
        "ShortVIN": "...2MH8E3",
        "VIN": "ZD3MZ5GYPJM2MH8E3",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569229",
        "AppointmentTime": "11:30 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$82.91 "
    },
    {
        "RONumber": "6478228",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Matthew Greenaway",
        "Advisor": "King Villanueva",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:00",
        "HangTag": "358",
        "ShortVIN": "...2S81MW",
        "VIN": "KNMWWUCXTC42S81MW",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569230",
        "AppointmentTime": "1:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C/I",
        "Warranty": "",
        "Internal": "$82.12 ",
        "Service Contract": "",
        "Customer Pay": "$83.96 "
    },
    {
        "RONumber": "6478229",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Mylah Sharpe",
        "Advisor": "Eric Sanders",
        "Service Type": "QL/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "359",
        "ShortVIN": "...WWME15",
        "VIN": "2BPV9YVZSHBWWME15",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569231",
        "AppointmentTime": "8:00 AM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$87.09 "
    },
    {
        "RONumber": "6478230",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Kaira Gentry",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL/BS",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "360",
        "ShortVIN": "...19SJAE",
        "VIN": "2WL3V5CZBRW19SJAE",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569232",
        "AppointmentTime": "4:30 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Pending",
        "PayType": "W",
        "Warranty": "$945.78 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478231",
        "Line Number": "1",
        "ROStatus": "In Process",
        "CustomerName": "Xena Higgins",
        "Advisor": "Susan Barber",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "361",
        "ShortVIN": "...JDKCNU",
        "VIN": "JHE6TY1XGY6JDKCNU",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Impala",
        "AppointmentID": "9187569233",
        "AppointmentTime": "2:00 PM",
        "AppointmentDate": "5-Dec",
        "ApppointmentStatus": "Checked In",
        "Tech": "Default",
        "TechStatus": "Unassigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Requested",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$62.73 "
    },
    {
        "RONumber": "6478232",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Kim Campos",
        "Advisor": "Eliza George",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "362",
        "ShortVIN": "...328303",
        "VIN": "1GNKRGED4BJ328304",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Volt",
        "AppointmentID": "9187569234",
        "AppointmentTime": "9:30 AM",
        "AppointmentDate": "6-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Unassigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$301.21 "
    },
    {
        "RONumber": "6478233",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Ashanti Wynn",
        "Advisor": "King Villanueva",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "363",
        "ShortVIN": "...2Y8311",
        "VIN": "1F0PYCYB8FP2Y8312",
        "Year": "2017",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569235",
        "AppointmentTime": "9:00 AM",
        "AppointmentDate": "7-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Unassigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "S",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "$553.75 ",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478234",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Luisa Quintana",
        "Advisor": "Latisha Wyatt",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "364",
        "ShortVIN": "...143747",
        "VIN": "WDDSJ4GB6EN143748",
        "Year": "2018",
        "Make": "Chevrolet",
        "Model": "Corvett",
        "AppointmentID": "9187569236",
        "AppointmentTime": "9:00 AM",
        "AppointmentDate": "8-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$246.57 "
    },
    {
        "RONumber": "6478235",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Mylo Enriquez",
        "Advisor": "King Villanueva",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "365",
        "ShortVIN": "...360627",
        "VIN": "1GCVKPEHXEZ360628",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Blazer",
        "AppointmentID": "9187569237",
        "AppointmentTime": "7:30 AM",
        "AppointmentDate": "9-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Accepted",
        "WarrantyStatusDealer": "Reconciled",
        "PayType": "W",
        "Warranty": "$174.39 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    },
    {
        "RONumber": "6478236",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Massimo Dudley",
        "Advisor": "Eric Sanders",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:45",
        "HangTag": "366",
        "ShortVIN": "...228591",
        "VIN": "1G2FW2180HN228592",
        "Year": "2020",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569238",
        "AppointmentTime": "7:30 AM",
        "AppointmentDate": "10-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$41.38 "
    },
    {
        "RONumber": "6478237",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Aubree Russo",
        "Advisor": "Taha Rodrigues",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "367",
        "ShortVIN": "...051392",
        "VIN": "SCBBR93W18C051393",
        "Year": "2021",
        "Make": "Chevrolet",
        "Model": "Tahoe",
        "AppointmentID": "9187569239",
        "AppointmentTime": "8:00 AM",
        "AppointmentDate": "11-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Joe Smith",
        "TechStatus": "Unassigned",
        "PartsPerson": "Brandon Hayes",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$78.73 "
    },
    {
        "RONumber": "6478238",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Samia Smith",
        "Advisor": "Susan Barber",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "368",
        "ShortVIN": "...511000",
        "VIN": "2HGFG3B55FH511001",
        "Year": "2022",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569240",
        "AppointmentTime": "7:30 AM",
        "AppointmentDate": "12-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Martin Hernandez",
        "TechStatus": "Unassigned",
        "PartsPerson": "Katherine Obrien",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$69.59 "
    },
    {
        "RONumber": "6478239",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Cassian Salt",
        "Advisor": "Eliza George",
        "Service Type": "QL",
        "Promised Date": "5-Dec",
        "PromisedTime": "4:30",
        "HangTag": "369",
        "ShortVIN": "...B24272",
        "VIN": "1FDKF37G4VEB24273",
        "Year": "2023",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569241",
        "AppointmentTime": "8:00 AM",
        "AppointmentDate": "13-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Maria Sanchez",
        "TechStatus": "Unassigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Waiter",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Paid",
        "WarrantyStatusOEM": "Default",
        "WarrantyStatusDealer": "Default",
        "PayType": "C",
        "Warranty": "",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": "$70.64 "
    },
    {
        "RONumber": "6478240",
        "Line Number": "1",
        "ROStatus": "Finalized",
        "CustomerName": "Lily Edge",
        "Advisor": "King Villanueva",
        "Service Type": "MR",
        "Promised Date": "5-Dec",
        "PromisedTime": "5:15",
        "HangTag": "370",
        "ShortVIN": "...018915",
        "VIN": "JHMBA4131JC018916",
        "Year": "2019",
        "Make": "Chevrolet",
        "Model": "Bolt",
        "AppointmentID": "9187569242",
        "AppointmentTime": "8:30 AM",
        "AppointmentDate": "14-Dec",
        "ApppointmentStatus": "Completed",
        "Tech": "Jeff Booker",
        "TechStatus": "Unassigned",
        "PartsPerson": "Alex Flores",
        "PartsStatus": "Approved",
        "TransportationType": "Rideshare",
        "InternalStatus": "Default",
        "ServiceContractStatus": "Default",
        "PaymentStatus": "Default",
        "WarrantyStatusOEM": "Discrepancy",
        "WarrantyStatusDealer": "Submited to OEM",
        "PayType": "W",
        "Warranty": "$865.87 ",
        "Internal": "",
        "Service Contract": "",
        "Customer Pay": ""
    }
],;
  return rowData;
}
